### ISSUE TITLE
Additional custom step functions

### ISSUE THREAD

**Issue by dylan-hoefsloot** [paul/dry-transaction-extra#1]
Hi, a big thanks for this gem.

I just watched your [talk](https://www.youtube.com/watch?v=YXiqzHMmv_o) from RubyConf 2021 and came to your github profile looking to see if you had shared any of the custom step functions you talked about.

Boy was I lucky that this gem has just been created a month ago.

I understand that this gem is very new, but I was just wondering if you were intending to add `async` and `authorize` step functions in future. I saw that you had implemented them previously in a [gist](https://gist.github.com/paul/b29b366d87880f91d8bb881dedddfcdb)

I also note the README does also provide an [example](https://github.com/paul/dry-transaction-extra#validation) of how you might use validation before running async jobs, is this your preferred approach now, rather than using a custom step function?

Anyway, if adding these is not part of your future plans and you have no objection to them being included, I wondered if I might try adding them in a PR?

Cheers, Dylan

**Comment by paul** [comment]
Hi @dylan-hoefsloot! Thanks for the kind words.

I want to add the `async` step to this gem, but the implementation I used at my day job was heavily dependent upon Rails and ActiveJob specifics, and I didn't want this gem to be Rails-specific. Also, in our implementation most of the code was in the app, in a base `ApplicationTransaction` and a specific `TransactionJob`, very little belonged to the `async` step adapter. In fact, its almost identical to the `use` step, replacing the `txn.call(*args)` with `TransactionJob.perform_later(txn.class.name, *args)`.

I'm still noodling on how to best accomplish this within the gem, but if you want more specifics I'd be happy to whip up an example in a Gist or something.

**Comment by dylan-hoefsloot** [comment]
Hi @paul, thanks for the reply.

That makes perfect sense, I've also realised the `authorize` step is pretty easy to accomplish without a custom step function.

```ruby
check :authorized?

def authorized?(resource:, user:)
  Pundit.policy(user, resource).manage?
end
```
