### ISSUE TITLE
Validate extension block behaviour

### ISSUE THREAD

**Issue by dylan-hoefsloot** [paul/dry-transaction-extra#2]
I have been using the [validation extension](https://github.com/paul/dry-transaction-extra#validation), however I have noticed that it has to be explicitly called on the object otherwise it is not run.

The [documentation](https://github.com/paul/dry-transaction-extra#validation) reads
> In addition to the [valid](https://github.com/paul/dry-transaction-extra#valid) step adapter, Dry::Transaction::Extra has support for an explicit "pre-flight" validation that runs as the first step.
```ruby
class CreateUser
  include Dry::Transaction
  include Dry::Transaction::Extra
  load_extensions :validation

  validate do
    params do
      required(:name).filled(:string)
      optional(:email).maybe(:string)
    end
  end

  step :create_user
end
```
> This is useful if you want to, for example, run the transaction as an async background job, but want to first verify the arguments to the job before enqueueing it. If the job is going to fail anyway, why bother creating it in the first place?
```ruby
result = CreateUser.validator.new.call(params)
CreateUserJob.perform_async(params) unless result.failure?
```

### Problem

Correct me If I am misunderstanding, but I took this to read that the validation will automatically be run as the first step when calling `CreateUser.new.call(params)` in addition to being able to call it explicitly with `CreateUser.validator.new.call(params)`

I could instead use the `valid` step function, however for small uncomplicated validations I find the brief extension syntax and lack of an additional file to be easier.

**Comment by paul** [comment]
You're correct, it is the intent that using the `validator` should create the validation and use it as the first step. There's some tests around this behavior as well: https://github.com/paul/dry-transaction-extra/blob/main/spec/integration/validation_dsl_spec.rb#L14-L30

Is that not what's happening for you? If not, can you provide a minimal test case I can investigate?

**Comment by dylan-hoefsloot** [comment]
I'll try to make a test case tonight,

I have just noticed that it does seem to be running, at least partially, however it runs as the last step rather than the first.

**Comment by paul** [comment]
I've been using this myself for awhile, and haven't noticed this behavior. I'm going to close this for now, but if you're able to reproduce it with an example, I'd be happy to take a look.
